def options(ctx): pass

def configure(ctx): pass

def build(bld):
  bld.shlib(
    source = '''
        classifier_base.cpp
	perceptron.cpp
	pa.cpp
	pa1.cpp
	pa2.cpp
	cw.cpp	
	arow.cpp
	nherd.cpp
        classifier_factory.cpp
	''',
    target = 'jubaclassifier',
    name = 'jubaclassifier',
    includes = '.',
    use = 'PFICOMMON')

  bld.program(
     features = 'gtest',
     source = [
         'classifier_test.cpp',
         'classifier_factory.cpp'   
     ],
     target = "classifier_test",
     includes = '.',
     use = 'jubaclassifier jubastorage')
