// this program is automatically generated by jenerator. do not edit.
#include "../framework.hpp"
#include "anomaly_server.hpp"
#include "anomaly_serv.hpp"
using namespace jubatus;
using namespace jubatus::framework;
namespace jubatus { namespace server {
class anomaly_impl_ : public anomaly<anomaly_impl_>
{
public:
  anomaly_impl_(const server_argv& a):
    anomaly<anomaly_impl_>(a.timeout),
    p_(new server_helper<anomaly_serv>(a, true))
  {}

  std::string get_config(std::string name) //analysis random
  { JRLOCK__(p_); return get_p()->get_config(); }

  bool clear_row(std::string name, std::string id) //update cht(2)
  { JWLOCK__(p_); return get_p()->clear_row(id); }

  std::pair<std::string,float > add(std::string name, datum d) //update random
  { JWLOCK__(p_); return get_p()->add(d); }

  float update(std::string name, std::string id, datum d) //update cht(2)
  { JWLOCK__(p_); return get_p()->update(id, d); }

  bool clear(std::string name) //update broadcast
  { JWLOCK__(p_); return get_p()->clear(); }

  float calc_score(std::string name, datum d) //analysis random
  { JRLOCK__(p_); return get_p()->calc_score(d); }

  std::vector<std::string > get_all_rows(std::string name) //analysis broadcast
  { JRLOCK__(p_); return get_p()->get_all_rows(); }

  bool save(std::string name, std::string arg1) //update broadcast
  { JWLOCK__(p_); return get_p()->save(arg1); }

  bool load(std::string name, std::string arg1) //update broadcast
  { JWLOCK__(p_); return get_p()->load(arg1); }

  std::map<std::string,std::map<std::string,std::string > > get_status(std::string name) //analysis broadcast
  { JRLOCK__(p_); return p_->get_status(); }
  int run(){ return p_->start(*this); };
  common::cshared_ptr<anomaly_serv> get_p(){ return p_->server(); };
private:
  common::cshared_ptr<server_helper<anomaly_serv> > p_;
};
}} // namespace jubatus::server
int main(int args, char** argv){
  return
    jubatus::framework::run_server<jubatus::server::anomaly_impl_>
       (args, argv, "anomaly");
}
