// this program is automatically generated. do not edit. 
#include "classifier_server.hpp"
#include "server_util.hpp"
#include "classifier_serv.hpp"
#include <pficommon/lang/shared_ptr.h>
#include <pficommon/concurrent/lock.h>

namespace jubatus { namespace server {

class classifier_impl_ : public classifier<classifier_impl_> 
{
public:
  classifier_impl_(int args, char** argv)
    : p_(new classifier_serv(args, argv)){};

  int set_config(std::string, config_data arg0) //@broadcast
  { pfi::concurrent::scoped_lock lk(wlock(p_->get_rw_mutex()));
    return p_->set_config(arg0); };

  config_data get_config(std::string, int arg0) //@random
  { JRLOCK__(p_);
    return p_->get_config(arg0); };

  int train(std::string, std::vector<std::pair<std::string, datum> >  arg0) //@random
  { JWLOCK__(p_);
    return p_->train(arg0); };

  std::vector<std::vector<estimate_result> >  classify(std::string, std::vector<datum>  arg0) //@random
  { JRLOCK__(p_);
    return p_->classify(arg0); };

  // autogenerated by generator
  std::string get_diff(int arg0)
  { JRLOCK__(p_);
    return p_->get_diff_impl(arg0); };

  int put_diff(std::string arg0)
  { JWLOCK__(p_);
    return p_->put_diff_impl(arg0); };

  int save(std::string, std::string arg0)//@broadcast
  { JRLOCK__(p_);
    return p_->save(arg0); };

  int load(std::string, std::string arg0) //@broadcast
  { JWLOCK__(p_);
    return p_->load(arg0); };

  int run(){ return p_->start(this); };

private:
  pfi::lang::shared_ptr<classifier_serv> p_;
};

}} // jubatus::server
int main(int args, char** argv){
  return jubatus::run_server<jubatus::server::classifier_impl_>(args, argv);
}
