// this program is automatically generated by jenerator. do not edit.
#include "../framework/keeper.hpp"
#include "../framework/aggregators.hpp"
#include "graph_types.hpp"
using namespace jubatus;
using namespace jubatus::framework;
int main(int args, char** argv){
  keeper k(keeper_argv(args,argv));
  k.register_random<std::string >("create_node"); //random update
  k.register_cht<int >("remove_node", pfi::lang::function<int(int,int)>(&random<int >)); //update
  k.register_cht<int, property >("update_node", pfi::lang::function<int(int,int)>(&all_and)); //update
  k.register_cht<int, edge_info >("create_edge", pfi::lang::function<int(int,int)>(&all_and)); //update
  k.register_cht<int, edge_id_t, edge_info >("update_edge", pfi::lang::function<int(int,int)>(&all_and)); //update
  k.register_cht<int, edge_id_t >("remove_edge", pfi::lang::function<int(int,int)>(&all_and)); //update
  k.register_random<double, std::string, centrality_type, preset_query >("centrality"); //pass analysis
  k.register_broadcast<bool, preset_query >("add_cenrality_query", pfi::lang::function<bool(bool,bool)>(&all_and)); //update
  k.register_broadcast<bool, preset_query >("add_shortest_path_query", pfi::lang::function<bool(bool,bool)>(&all_and)); //update
  k.register_broadcast<bool, preset_query >("remove_cenrality_query", pfi::lang::function<bool(bool,bool)>(&all_and)); //update
  k.register_broadcast<bool, preset_query >("remove_shortest_path_query", pfi::lang::function<bool(bool,bool)>(&all_and)); //update
  k.register_random<std::vector<node_id >, shortest_path_req >("shortest_path"); //pass analysis
  k.register_broadcast<int >("update_index", pfi::lang::function<int(int,int)>(&all_and)); //update
  k.register_broadcast<int >("clear", pfi::lang::function<int(int,int)>(&all_and)); //update
  k.register_cht<node_info >("get_node", pfi::lang::function<node_info(node_info,node_info)>(&random<node_info >)); //analysis
  k.register_cht<edge_info, edge_id_t >("get_edge", pfi::lang::function<edge_info(edge_info,edge_info)>(&random<edge_info >)); //analysis
  k.register_broadcast<bool, std::string >("save", pfi::lang::function<bool(bool,bool)>(&all_and)); //update
  k.register_broadcast<bool, std::string >("load", pfi::lang::function<bool(bool,bool)>(&all_and)); //update
  k.register_broadcast<std::map<std::string,std::map<std::string,std::string > > >("get_status", pfi::lang::function<std::map<std::string,std::map<std::string,std::string > >(std::map<std::string,std::map<std::string,std::string > >,std::map<std::string,std::map<std::string,std::string > >)>(&merge<std::string,std::map<std::string,std::string > >)); //analysis
  k.run();
}
