// this program is automatically generated by jenerator. do not edit.
#include "../framework/keeper.hpp"
#include "../framework/aggregators.hpp"
#include "../common/exception.hpp"
#include "stat_types.hpp"
#include <glog/logging.h>
using namespace jubatus;
using namespace jubatus::framework;
int main(int args, char** argv){
  try{
    keeper k(keeper_argv(args,argv,"stat"));
    k.register_broadcast<bool, config_data >("set_config", pfi::lang::function<bool(bool,bool)>(&all_and)); //update
    k.register_random<config_data >("get_config"); //pass analysis
    k.register_cht<1, bool, double >("push", pfi::lang::function<bool(bool,bool)>(&all_and)); //update
    k.register_cht<1, double >("sum", pfi::lang::function<double(double,double)>(&pass<double >)); //analysis
    k.register_cht<1, double >("stddev", pfi::lang::function<double(double,double)>(&pass<double >)); //analysis
    k.register_cht<1, double >("max", pfi::lang::function<double(double,double)>(&pass<double >)); //analysis
    k.register_cht<1, double >("min", pfi::lang::function<double(double,double)>(&pass<double >)); //analysis
    k.register_cht<1, double >("entropy", pfi::lang::function<double(double,double)>(&pass<double >)); //analysis
    k.register_cht<1, double, int, double >("moment", pfi::lang::function<double(double,double)>(&pass<double >)); //analysis
    k.register_broadcast<bool, std::string >("save", pfi::lang::function<bool(bool,bool)>(&all_and)); //update
    k.register_broadcast<bool, std::string >("load", pfi::lang::function<bool(bool,bool)>(&all_and)); //update
    k.register_broadcast<std::map<std::string,std::map<std::string,std::string > > >("get_status", pfi::lang::function<std::map<std::string,std::map<std::string,std::string > >(std::map<std::string,std::map<std::string,std::string > >,std::map<std::string,std::map<std::string,std::string > >)>(&merge<std::string,std::map<std::string,std::string > >)); //analysis
    return k.run();
  } catch (const jubatus::exception::jubatus_exception& e) {
    LOG(FATAL) << e.diagnostic_information(true);
    return -1;
  }
}
