def configure(conf):
  pass

def build(bld):
  bld.install_files('${HPREFIX}/lang/algorithm', [
      'copy_if.h'
      ])

  bld.program(
    features = 'gtest',
    source = 'algorithm_test.cpp',
    target = 'algorithm_test',
    includes = '.')
