# -*- python -*-
import Options

subdirs = '''
column
'''

def options(opt):
  opt.recurse(subdirs)

def configure(conf):
  conf.recurse(subdirs)

def build(bld):
  headers = [
      'storage_exception.hpp',
      ]
  bld.core_headers.extend(bld.add_prefix(headers))
  bld.recurse(subdirs)
