# -*- python -*-
import Options

subdirs = '''
column
'''

def options(opt):
  opt.recurse(subdirs)

def configure(conf):
  conf.recurse(subdirs)

def build(bld):
  bld.install_files('${PREFIX}/include/jubatus/core/table/', [
      'storage_exception.hpp',
      ])
  bld.recurse(subdirs)
