def options(opt):
    pass

def configure(conf):
    pass

def build(bld):
    if not bld.is_defined('JUBATUS_DISABLE_ASSERTIONS'):
        libassert = " LIBGLOG"
    else:
        libassert = ""

    bld.shlib(
        source = [
            'regression_base.cpp',
            'passive_aggressive.cpp',
            'regression_factory.cpp'
            ],
        target = 'jubatus_regression',
        includes = '.',
        use = 'jubatus_util jubacommon jubatus_mixables'+libassert
        )

    def make_test(s):
        bld.program(
            features = 'gtest',
            source = s,
            target = s[0: s.rfind('.')],
            includes = '.',
            use = 'jubatus_regression jubastorage'+libassert
            )

    test_source = [
        'regression_test.cpp',
        'regression_factory_test.cpp',
        ]
    for s in test_source:
        make_test(s)

    bld.install_files('${PREFIX}/include/jubatus/core/regression', [
        'regression_base.hpp',
        'regression_factory.hpp',
        ])
