def options(opt): pass

def configure(conf): pass

def build(bld):
  if bld.env.HAVE_ZOOKEEPER_H:
    bld.program(
      source = 'jubactl.cpp',
      target = 'jubactl',
      use = 'MSGPACK jubatus_util LIBGLOG ZOOKEEPER_MT jubatus_core jubaserv_common jubaserv_framework JUBATUS_MPIO JUBATUS_MSGPACK-RPC MSGPACK core_headers'
      )

    bld.program(
      source = 'jubaconfig.cpp',
      target = 'jubaconfig',
      use = 'jubatus_util LIBGLOG ZOOKEEPER_MT jubatus_core jubaserv_common core_headers'
      )


  bld.program(
    source = 'jubaconv.cpp',
    target = 'jubaconv',
    use = 'jubatus_util jubatus_core jubaconverter jubaserv_common core_headers'
    )
