incdirs = '. encoding digest string'

def configure(conf):
  conf.check_cxx(header_name = 'stdint.h')

  conf.check_cxx(header_name = 'unordered_map', mandatory = False)
  conf.check_cxx(header_name = 'tr1/unordered_map', mandatory = False)
  conf.check_cxx(header_name = 'ext/hash_map', mandatory = False)
  conf.check_cxx(header_name = 'unordered_set', mandatory = False)
  conf.check_cxx(header_name = 'tr1/unordered_set', mandatory = False)
  conf.check_cxx(header_name = 'ext/hash_set', mandatory = False)

def build(bld):
  bld.install_files('${HPREFIX}/data', [
      'optional.h',
      'serialization.h',
      'serialization/array.h',
      'serialization/base.h',
      'serialization/reflect.h',
      'serialization/string.h',
      'serialization/vector.h',
      'serialization/deque.h',
      'serialization/list.h',
      'serialization/set.h',
      'serialization/map.h',
      'serialization/unordered_map.h',
      'serialization/tr1_unordered_map.h',
      'serialization/unordered_set.h',
      'serialization/tr1_unordered_set.h',
      'serialization/pair.h',
      'serialization/iostream.h',
      'string/utility.h',
      'unordered_map.h',
      'unordered_set.h',
      'functional_hash.h',
      ], relative_trick = True)
