def options(ctx): pass

def configure(ctx): pass

def build(bld):
  bld.shlib(
    source = '''
    	  recommender_base.cpp
	  inverted_file.cpp
	  lsh.cpp
	  minhash.cpp
	 ''',
    target = 'jubarecommender_new',
    name = 'jubarecommender_new',
    include = '.',
    use = 'PFICOMMON jubastorage jubacommon')

  bld.shlib(
    source = '''
    	 similarity_factory.cpp
	 anchor_builder_factory.cpp
	 anchor_finder_factory.cpp
	 recommender.cpp
	 recommender_builder.cpp
	 anchor_builder_base.cpp
	 anchor_builder_random.cpp
	 anchor_finder_naive.cpp
	 anchor_finder_knndecent.cpp
	''',
    target = 'jubarecommender',
    name = 'jubarecommender',
    includes = '.',
    use = 'PFICOMMON jubastorage jubacommon')

  def make_test(s):
    bld.program(
      features = 'gtest',
      source = s,
      target = s[0:s.rfind('.')],
      includes = '.',
      use = 'PFICOMMON jubarecommender jubacommon jubarecommender_new')

  map(make_test, [
      'recommender_test.cpp',
      'recommender_base_test.cpp',
      ])
