def options(ctx): pass

def configure(ctx): pass

def build(bld):
  bld.shlib(
    source = '''
    	  recommender_base.cpp
	  inverted_index.cpp
	  lsh.cpp
	  minhash.cpp
	  recommender_factory.cpp
	 ''',
    target = 'jubarecommender',
    name = 'jubarecommender',
    include = '.',
    use = 'PFICOMMON jubastorage jubacommon')

  def make_test(s):
    bld.program(
      features = 'gtest',
      source = s,
      target = s[0:s.rfind('.')],
      includes = '.',
      use = 'PFICOMMON jubarecommender jubacommon jubarecommender_new')

  map(make_test, [
      'recommender_test.cpp',
      'recommender_base_test.cpp',
      ])
