def options(opt):
  pass

def configure(conf):
  pass

def build(bld):

  source = [
      'model.cpp',
      'mixable.cpp',
      'push_mixable.cpp',
      'linear_mixable.cpp',
      'mixable_helper.cpp',
      ]
  headers = [
      'linear_mixable.hpp',
      'mixable.hpp',
      'mixable_helper.hpp',
      'model.hpp',
      'new_mixable.hpp',
      'packer.hpp',
      'push_mixable.hpp',
      ]
  use = ['jubatus_util']

  bld.core_sources.extend(bld.add_prefix(source))
  bld.core_headers.extend(bld.add_prefix(headers))
  bld.core_use.extend(use)

  def make_test(t):
    bld.program(
      features='gtest',
      source=t + '.cpp',
      target=t,
      includes='.',
      use = ['jubatus_util', 'MSGPACK', 'jubatus_core'])

  tests = [
    'mixable_test',
    ]

  for t in tests:
    make_test(t)

