def options(opt):
  pass

def configure(conf):
  pass

def build(bld):
  if not bld.is_defined('JUBATUS_DISABLE_ASSERTIONS'):
    libassert = " LIBGLOG"
  else:
    libassert = ""

  src = 'model.cpp mixable.cpp push_mixable.cpp linear_mixable.cpp mixable_helper.cpp'
  bld.shlib(
    source = src,
    target = 'jubacore',
    includes = '.',
    use = 'jubatus_util'+libassert
    )

  def make_test(t):
    bld.program(
      features='gtest',
      source=t + '.cpp',
      target=t,
      includes='.',
      use='MSGPACK jubacore jubacommon jubatus_util'+libassert,
      )

  tests = [
    'mixable_test',
    ]

  for t in tests:
    make_test(t)

  bld.install_files('${PREFIX}/include/jubatus/core/framework', [
      'mixable.hpp',
      ])
