# -*- python -*-
def options(opt): pass

def configure(conf): pass

def build(bld):
  if bld.env.HAVE_ZOOKEEPER_H:
    bld.program(
      source = 'jubactl.cpp',
      target = 'jubactl',
      includes = '.',
      use = 'MSGPACK PFICOMMON LIBGLOG ZOOKEEPER_MT jubacommon jubatus_framework JUBATUS_MPIO JUBATUS_MSGPACK-RPC MSGPACK' 
      )

    bld.program(
      source = 'jubaconfig.cpp',
      target = 'jubaconfig',
      includes = '.',
      use = 'PFICOMMON LIBGLOG ZOOKEEPER_MT jubacommon'
      )


  bld.program(
    source = 'jubaconv.cpp',
    target = 'jubaconv',
    includes = '.',
    use = 'PFICOMMON jubacommon jubaconverter'
    )
