#!/usr/bin/env python

subdirs = ['recommender']

def options(opt):
  opt.recurse(subdirs)

def configure(conf):
  conf.recurse(subdirs)

def build(bld):
  bld.install_files('${INCLUDEDIR}/jubatus/inprocess', 'common.h')

  bld.recurse(subdirs)
