def options(ctx): pass

def configure(ctx): pass

def build(bld):
  source = [
      'classifier_base.cpp',
      'perceptron.cpp',
      'passive_aggressive.cpp',
      'passive_aggressive_1.cpp',
      'passive_aggressive_2.cpp',
      'confidence_weighted.cpp',
      'arow.cpp',
      'normal_herd.cpp',
      'classifier_factory.cpp',
      ]
  headers = [
      'classifier_base.hpp',
      'classifier_factory.hpp',
      'classifier_type.hpp',
      'classifier_config.hpp',
      ]
  use = ['jubatus_util']

  bld.core_sources.extend(bld.add_prefix(source))
  bld.core_headers.extend(bld.add_prefix(headers))
  bld.core_use.extend(use)

  bld.program(
     features = 'gtest',
     source = [
         'classifier_test.cpp',
         'classifier_factory.cpp'
     ],
     target = "classifier_test",
     includes = '.',
     use = ['jubatus_util', 'jubatus_core'])

