def options(opt):
    pass

def configure(conf):
    pass

def build(bld):
    bld.shlib(
        source = [
            'regression_base.cpp',
            'online_svr.cpp',
            ],
        target = 'jubaression',
        includes = '.',
        use = 'PFICOMMON jubacommon'
        )

    bld.program(
        features = 'gtest',
        source = 'regression_test.cpp',
        target = 'regression_test',
        includes = '.',
        use = 'jubaression jubastorage'
        )
