import Options

subdirs = "anomaly classifier driver fv_converter graph recommender regression stat storage"

def options(opt):
  opt.recurse(subdirs)

def configure(conf):
  conf.recurse(subdirs)

def build(bld):
  bld.recurse(subdirs)
  # bld.install_files('${PREFIX}/include/jubatus',
  #                   ['config.hpp', 'client.hpp', 'plugin.hpp', 'framework.hpp'])
