import Options

subdirs = "src"

def options(opt):
  opt.recurse(subdirs)

def configure(conf):
  conf.recurse(subdirs)

def build(bld):
  bld(name = 'core_headers', export_includes = 'src')
  bld.recurse(subdirs)
  # bld.install_files('${PREFIX}/include/jubatus',
  #                   ['config.hpp', 'client.hpp', 'plugin.hpp', 'framework.hpp'])
