
def options(opt): pass
    

def configure(conf): pass

def build(bld):
  src = 'rpc_client.cpp async_client.cpp'

  bld.stlib(
    source = src,
    target = 'jubacommon_mprpc',
    includes = '.',
    use = 'PFICOMMON GLOG ZOOKEEPER_MT CRYPT'
    )

  #bld.install_files('${PREFIX}/include/jubatus/common/', bld.path.ant_glob('*.hpp'))
