
def options(opt): pass

def configure(conf): pass

def build(bld):
  src = 'rpc_mclient.cpp rpc_server.cpp'

  bld.shlib(
    source = src,
    target = 'jubacommon_mprpc',
    use = 'PFICOMMON LIBGLOG ZOOKEEPER_MT LIBEVENT JUBATUS_MPIO JUBATUS_MSGPACK-RPC MSGPACK jubacommon'
    )

  bld.program(
    features = 'gtest',
    source = 'rpc_client_test.cpp',
    target = 'rpc_client_test',
    includes = '.',
    use = 'PFICOMMON JUBATUS_MPIO JUBATUS_MSGPACK-RPC MSGPACK jubacommon jubacommon_mprpc',
    )

  bld.install_files('${PREFIX}/include/jubatus/common/mprpc', bld.path.ant_glob('*.hpp'))
