def options(opt):
  pass

def configure(conf):
  pass

def build(bld):
  if not bld.env.HAVE_ZOOKEEPER_H: return

  bld.program(
    source = 'main.cpp jubakeeper.cpp',
    target = 'jubakeeper',
    includes = '.',
    use = 'PFICOMMON GLOG ZOOKEEPER_MT jubacommon'
    )
