def options(opt):
  pass

def configure(conf):
  pass

def build(bld):
  bld.shlib(
    target = 'unlearner',
    source = [
      'lru_unlearner.cpp',
      'random_unlearner.cpp',
      'unlearner_factory.cpp'],
    use = 'jubacommon')

  bld.program(
    features = 'gtest',
    target = 'unlearner_test',
    source = [
      'lru_unlearner_test.cpp',
      'random_unlearner_test.cpp',
      'unlearner_base_test.cpp'],
    use = 'unlearner')
