#!/bin/sh

# please copy this file to .git/hooks/ and chmod +x

CPPLINT="tools/codestyle/cpplint/cpplint.py"
CPPLINT_ARGS="--filter=-runtime/references,-runtime/rtti"

codestyle_violation_count=$(git diff --cached --name-only | grep -v "^src/third_party/" | xargs "${CPPLINT}" "${CPPLINT_ARGS}" 2>&1 | grep Total | sed -e "s/[^0-9]*\([0-9]*\)/\1/")
echo $codestyle_violation_count
if [ $codestyle_violation_count != "0" ]
then
    git diff --cached --name-only | xargs "${CPPLINT}" "${CPPLINT_ARGS}"
    echo "Error: Please go along with Jubatus coding style when you commit"
    exit 1
else
    exit 0
fi
