def options(opt):
  pass

def configure(conf):
  pass

def build(bld):
  source = [
      'recommender.cpp',
      'mixable_weight_manager.cpp',
      ]

  bld.shlib(
    source = source,
    target = 'jubatus_driver',
    includes = '.',
    use = 'PFICOMMON jubacommon MSGPACK jubaconverter jubastorage jubatus_recommender'
    )

  bld.install_files('${PREFIX}/include/jubatus/core/driver', [
      'recommender.hpp',
      'mixable_weight_manager.hpp',
      'diffv.hpp',
      ])
