def options(ctx): pass

def configure(ctx): pass

def build(bld):
  bld.shlib(
    source = [
      'recommender_base.cpp',
      'inverted_index.cpp',
      'recommender_factory.cpp',
      ],
    target = 'jubatus_recommender',
    name = 'jubatus_recommender',
    includes = '.',
    use = 'PFICOMMON jubastorage jubacommon')

  def make_test(s):
    bld.program(
      features = 'gtest',
      source = s,
      target = s[0:s.rfind('.')],
      includes = '.',
      use = 'PFICOMMON jubatus_recommender jubacommon')

  bld.install_files('${PREFIX}/include/jubatus/core/recommender', [
      'recommender_base.hpp',
      'recommender_factory.hpp',
      'recommender_type.hpp',
      ])
