# -*- python -*-
subdirs = [
    'mecab_splitter',
    'ux_splitter',
    'image_feature',
    'python_bridge',
]


def options(opt):
    opt.recurse(subdirs)

def configure(conf):
    conf.recurse(subdirs)

def build(bld):
    bld.recurse(subdirs)
