service sample {
  #@random #@analysis #@pass
  string random_analysis_pass(0: string name)

  #@cht #@update #@all_and
  bool chd_update_alland(0: string name, 1: string id)

  #@broadcast #@nolock #@concat
  list<string> broadcast_nolock_concat(0: string name)

  #@random #@analysis #@merge
  list<string> random_analysis_merge(0: string name)

  #@broadcast #@analysis #@add
  float broadcast_analysis_add(0: string name)

  #@cht #@analysis #@add
  int cht_analysis_add(0: string name)
}
