# Jubatus: Online machine learning framework for distributed environment
# Copyright (C) 2011,2012 Preferred Infrastructure and Nippon Telegraph and Telephone Corporation.
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License version 2.1 as published by the Free Software Foundation.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

message st_keyword {
  0: string txt
  1: double scaling_param
  2: double gamma
}

message st_batch {
  0: int d
  1: int r
  2: double batch_weight
}

message st_window {
  0: int start_pos
  1: list<st_batch> batches
}

message st_document {
  0: double pos
  1: datum txt
}

service burst {

  #@broadcast #@update #@all_and
  bool add_documents(0: list<st_document> data) # //@broadcast

  #@cht #@analysis #@pass
  st_window get_result(0: string keyword_txt) # //@cht

  #@cht #@analysis #@pass
  st_window get_result_at(0: string keyword_txt, 2: double pos) # //@cht

  #@broadcast #@analysis #@merge
  map<string, st_window > get_all_bursted_results() # //@broadcast

  #@broadcast #@analysis #@merge
  map<string, st_window > get_all_bursted_results_at(0: double pos) # //@broadcast

  #@random #@analysis #@pass
  list<st_keyword> get_all_keywords() # //@random

  #@broadcast #@update #@all_and
  bool add_keyword(0: st_keyword keyword) # //@broadcast

  #@broadcast #@update #@all_and
  bool remove_keyword(0: string keyword_txt) # //@broadcast

  #@broadcast #@update #@all_and
  bool remove_all_keywords() # //@broadcast
}
