# Jubatus: Online machine learning framework for distributed environment
# Copyright (C) 2011-2013 Preferred Infrastructure and Nippon Telegraph and Telephone Corporation.
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License version 2.1 as published by the Free Software Foundation.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

%include "../../core/fv_converter/datum.hpp"
%include "../../core/cluster_analysis/cluster_analysis_types.hpp"


message weighted_datum("std::pair<double, jubatus::core::fv_converter::datum>") {
  0: double weight
  1: datum point
}

message cluster_relation("jubatus::core::cluster_analysis::cluster_relation") {
  0: int cluster1
  1: int cluster2
  2: double similarity
}

message change_graph("jubatus::core::cluster_analysis::change_graph") {
  0: string snapshot_name1
  1: string snapshot_name2
  2: list<cluster_relation> related_pairs
}

message clustering_snapshot("jubatus::core::cluster_analysis::clustering_snapshot") {
  0: string name
  1: list<list<weighted_datum> > clusters
}

service cluster_analysis {
  #@broadcast #@update #@all_and
  bool add_snapshot(0: string clustering_name)

  #@random #@analysis #@pass
  list<change_graph> get_history()

  #@random #@analysis #@pass
  list<clustering_snapshot> get_snapshots()
}
