message id_with_score("std::pair<std::string, float>") {
  0: string id
  1: float score
}

service nearest_neighbor {
  #@broadcast #@update #@all_and
  bool clear()

  #@cht(1) #@update #@pass
  bool set_row(0: string id, 1: datum d)

  #@random #@analysis #@pass
  list<id_with_score> neighbor_row_from_id(0: string id, 1: uint size)

  #@random #@analysis #@pass
  list<id_with_score> neighbor_row_from_data(0: datum query, 1: uint size)

  #@random #@analysis #@pass
  list<id_with_score> similar_row_from_id(0: string id, 1: int ret_num)

  #@random #@analysis #@pass
  list<id_with_score> similar_row_from_data(0: datum query, 1: int ret_num)
}
