# -*- python -*-
def options(opt):
    pass

def configure(conf):
    pass

def build(bld):
  if not bld.is_defined('JUBATUS_DISABLE_ASSERTIONS'):
    libassert = " LIBGLOG"
  else:
    libassert = ""

  bld.shlib(
    source = [
        'column_table.cpp',
    ],
    target = 'column_table',
    name = 'column_table',
    use = 'PFICOMMON'+libassert
  )

  def make_test(s):
    bld.program(
      features = 'gtest',
      source = s,
      target = s[0:s.rfind('.')],
      includes = '.',
      use = 'MSGPACK PFICOMMON column_table jubacommon'+libassert)
  map(make_test,['column_table_test.cpp',
                 'column_type_test.cpp',
                 'bit_vector_test.cpp'])

  bld.install_files('${PREFIX}/include/jubatus/core/table/column/', [
      'abstract_column.hpp',
      'bit_vector.hpp',
      'column_table.hpp',
      'column_type.hpp',
      'owner.hpp',
      ])
