def options(opt): pass
def configure(conf): pass

def build(bld):
  source = ['stat.cpp']
  headers = ['stat.hpp']
  use = ['jubatus_util']

  bld.core_sources.extend(bld.add_prefix(source))
  bld.core_headers.extend(bld.add_prefix(headers))
  bld.core_use.extend(use)

  bld.program(
    features = 'gtest',
    source = [
      'stat_test.cpp',
      ],
    target = 'stat_test',
    includes = '.',
    use = ['jubatus_util', 'jubatus_core']
    )
