def options(opt):
  pass

def configure(conf):
  pass

def build(bld):

  # TODO: annomaly, graph, recommender, regression, stat
  core_source = 'classifier.cpp linear_function_mixer.cpp mixable_weight_manager.cpp'

  bld.shlib(
    source = core_source,
    target = 'jubatus_core',
    includes = '.',
    use = 'PFICOMMON jubacommon jubatus_framework MSGPACK LIBGLOG jubaconverter jubastorage jubamixer jubatus_classifier'
    )

  def make_test(t):
    bld.program(
      features='gtest',
      source=t + '.cpp',
      target=t,
      includes='.',
      use='jubatus_core'
      )

  tests = [
    'linear_function_mixer_test'
    ]

  for t in tests:
    make_test(t)

  bld.install_files('${PREFIX}/include/jubatus/core', [
      'classifier.hpp'
      ])
