import Options

def options(opt): pass

def configure(conf): pass

def make_test(bld, src):
  bld.program(
    features = 'gtest',
    source = src,
    target = src[0:src.rindex('.')],
    use = 'jubastorage',
    )

def make_tests(bld, srcs):
  for src in srcs:
    make_test(bld, src)

def build(bld):
  cppfiles = ['storage_factory.cpp', 'storage_base.cpp', 'local_storage.cpp',
              'local_storage_mixture.cpp', 'recommender_storage.cpp',
              'norm_none.cpp', 'norm_factory.cpp', 'norm_l1.cpp', 'norm_l2.cpp']
  use = 'PFICOMMON jubacommon MSGPACK'

  bld.shlib(
    source = cppfiles,
    target = 'jubastorage',
    includes = '.',
    use = use
    )

  make_tests(bld, [
      'storage_test.cpp',
      'storage_factory_test.cpp',
      'local_storage_mixture_test.cpp',
      'recommender_storage_test.cpp',
      ])

  bld.install_files('${PREFIX}/include/jubatus/server/storage',
                    'storage_type.hpp')
