# -*- python -*-
def options(opt):
  pass

def configure(conf):
  pass

def build(bld):
  source = [
      'nearest_neighbor_base.cpp',
      'nearest_neighbor_factory.cpp',
      'bit_vector_nearest_neighbor_base.cpp',
      'bit_vector_ranking.cpp',
      'minhash.cpp',
      'lsh.cpp',
      'lsh_function.cpp',
      'euclid_lsh.cpp'
    ]
  headers = [
      'bit_vector_nearest_neighbor_base.hpp',
      'bit_vector_ranking.hpp',
      'euclid_lsh.hpp',
      'exception.hpp',
      'lsh.hpp',
      'lsh_function.hpp',
      'minhash.hpp',
      'nearest_neighbor.hpp',
      'nearest_neighbor_base.hpp',
      'nearest_neighbor_factory.hpp',
      ]
  use = ['jubatus_util']

  bld.core_sources.extend(bld.add_prefix(source))
  bld.core_headers.extend(bld.add_prefix(headers))
  bld.core_use.extend(use)

  bld.program(
    target = 'nearest_neighbor_base_test',
    features = 'gtest',
    source = [
      'nearest_neighbor_base_test.cpp',
      'bit_vector_nearest_neighbor_base_test.cpp',
      'nearest_neighbor_test.cpp',
    ],
    use = ['jubatus_util', 'jubatus_core'])
