# -*- python -*-
def options(opt):
  pass

def configure(conf):
  pass

def build(bld):
  bld.shlib(
    source = [
      'nearest_neighbor_base.cpp',
      'nearest_neighbor_factory.cpp',
      'bit_vector_nearest_neighbor_base.cpp',
      'bit_vector_ranking.cpp',
      'minhash.cpp',
      'lsh.cpp',
      'lsh_function.cpp',
      'euclid_lsh.cpp'
    ],
    target = 'jubatus_nearest_neighbor',
    name = 'jubatus_nearest_neighbor',
    use = 'PFICOMMON')

  bld.shlib(
    target = 'nearest_neighbor',
    source = [
        'bit_vector_nearest_neighbor_base.cpp',
        'bit_vector_ranking.cpp',
        'euclid_lsh.cpp',
        'lsh.cpp',
        'lsh_function.cpp',
        'minhash.cpp',
        'nearest_neighbor_base.cpp',
        'nearest_neighbor_factory.cpp',
        ],
    use = 'PFICOMMON jubastorage column_table')

  bld.program(
    target = 'nearest_neighbor_base_test',
    features = 'gtest',
    source = [
      'nearest_neighbor_base_test.cpp',
      'bit_vector_nearest_neighbor_base_test.cpp',
      'nearest_neighbor_test.cpp',
    ],
    use = 'nearest_neighbor column_table')

  bld.install_files('${PREFIX}/include/jubatus/core/nearest_neighbor/', [
      'bit_vector_nearest_neighbor_base.hpp',
      'bit_vector_ranking.hpp',
      'euclid_lsh.hpp',
      'exception.hpp',
      'lsh.hpp',
      'lsh_function.hpp',
      'minhash.hpp',
      'nearest_neighbor.hpp',
      'nearest_neighbor_base.hpp',
      'nearest_neighbor_factory.hpp',
      ])
