
def options(opt): pass

def configure(conf): pass

def build(bld):
  src = 'logger.cpp'

  bld.shlib(
    source = src,
    target = 'jubaserv_common_logger',
    use = 'jubatus_util LIBLOG4CXX'
    )

  bld.install_files('${PREFIX}/include/jubatus/server/common/logger', bld.path.ant_glob('*.hpp'))
