# -*- python -*-
def options(opt):
  pass

def configure(conf):
  pass

def build(bld):
  mixer_framework = 'PFICOMMON MSGPACK LIBGLOG'
  mixer_source = 'mixer_factory.cpp'
  if bld.env.HAVE_ZOOKEEPER_H:
    mixer_framework += ' jubacommon jubacommon_mprpc'
    mixer_source += ' linear_mixer.cpp push_mixer.cpp'

  bld.shlib(target = 'jubamixer',
            source = mixer_source,
            use = mixer_framework)

  if bld.env.HAVE_ZOOKEEPER_H:
    bld.program(
      features='gtest',
      source = 'linear_mixer_test.cpp',
      target = 'linear_mixer_test',
      use = 'jubamixer'
      )

  bld.install_files('${PREFIX}/include/jubatus/framework/mixer', [
      'dummy_mixer.hpp',
      'linear_mixer.hpp',
      'mixer.hpp',
      'mixer_factory.hpp',
      'random_mixer.hpp',
      'skip_mixer.hpp',
      'broadcast_mixer.hpp'
      ])
