# IDL for Jubatus fv_converter


message string_rule {
  0: string key
  1: string type
  2: string sample_weight
  3: string global_weight
}

message filter_rule {
  0: string key
  1: string type
  2: string suffix
}

message num_rule {
  0: string key
  1: string type
}

type param_t = map<string, string>

message converter_config {
  0: map<string, param_t> string_filter_types
  1: list<filter_rule>    string_filter_rules
  2: map<string, param_t> num_filter_types
  3: list<filter_rule>    num_filter_rules
  4: map<string, param_t> string_types
  5: list<string_rule>    string_rules
  6: map<string, param_t> num_types
  7: list<num_rule>       num_rules
}

message datum {
  0: list<tuple<string, string>> sv
  1: list<tuple<string, double>> nv
}

