import Options

#subdirs = '''
#common server cmd jubavisor plugin
#classifier fv_converter recommender regression storage
#'''

subdirs = '''
common cmd jubavisor plugin
classifier fv_converter recommender regression storage attic
'''

def options(opt):
  opt.recurse(subdirs)

def configure(conf):
  conf.recurse(subdirs)

def build(bld):
  bld.recurse(subdirs)
  bld.install_files('${PREFIX}/include', 'jubatus.hpp')
  bld.install_files('${PREFIX}/include/jubatus', 'plugin.hpp')
