import Options

subdirs = '''
common plugin stat
classifier fv_converter recommender regression storage
framework servers
cmd jubavisor
'''

def options(opt):
  opt.recurse(subdirs)

def configure(conf):
  conf.recurse(subdirs)

def build(bld):
  bld.recurse(subdirs)
  bld.install_files('${PREFIX}/include', 'jubatus.hpp')
  bld.install_files('${PREFIX}/include/jubatus', 'plugin.hpp')
