#!/usr/bin/env python

def options(opt):
  pass

def configure(conf):
  pass

def build(bld):
  sources = ['recommender_wrapper.cpp']
  headers = ['recommender_wrapper.hpp']

  sources += ['recommender_wrapper_c.cpp']
  headers += ['recommender_wrapper_c.h']

  bld.shlib(
    source = sources,
    target = 'jubatus_inprocess_recommender',
    use = ['jubatus', 'jubatus_driver', 'jubatus_recommender',
           'jubastorage', 'jubaconverter', 'PFICOMMON'])

  bld.install_files('${INCLUDEDIR}/jubatus/inprocess/recommender', headers)
