import Options

subdirs = "common anomaly classifier driver framework fv_converter graph recommender regression stat storage nearest_neighbor table clustering unlearner third_party"

def options(opt):
  opt.recurse(subdirs)

def configure(conf):
  conf.recurse(subdirs)

def build(bld):
  headers = [
      'plugin.hpp',
      ]

  bld.core_headers.extend(bld.add_prefix(headers))

  bld.recurse(subdirs)
